name: nodejs-ex
replicaCount: 1

image:
  repository: 727245885999.dkr.ecr.us-west-2.amazonaws.com/nodejs-ex
  pullPolicy: Always
  tag: "prod-7ec31e9"

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
 type: NodePort
 port: 8000
 targetport: 3000

resources: 
  requests:
    cpu: 100m
    memory: 200m
container:
        port: 3000
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
namespace: "prod"

##for liveness and readiness  
path: "/"
port: 3000
